# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('usd', models.CharField(max_length=30, verbose_name='\u0414\u043e\u043b\u043b\u0430\u0440')),
                ('kgs', models.CharField(max_length=30, verbose_name='\u0421\u043e\u043c')),
            ],
        ),
    ]
