# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total_amount',
        ),
    ]
